import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'views/workout_list.dart';
import 'firebase_options.dart'; // Make sure this file is generated by Firebase CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Workout Tracker',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const WorkoutListView(),
    );
  }
}

// class AppTheme {
//   static final ThemeData themeData = ThemeData(
//     primarySwatch: Colors.blue,
//     primaryColor: Colors.blueAccent,
//     colorScheme: ColorScheme.fromSwatch().copyWith(
//       secondary: Colors.orangeAccent,
//     ),
//   );
// }